### ISSUE TITLE
StreamClosedByServerException: Stream closed by server

### ISSUE THREAD

**Issue by Depi1993** [launchdarkly/java-core#32]
Launch Darkly Configuration:

`implementation group: 'com.launchdarkly', name: 'launchdarkly-java-server-sdk', version: '6.0.4'`

With Config:

`new LDConfig.Builder()
            .http(Components.httpConfiguration()
                .connectTimeout(Duration.ofSeconds(LD_CONNECT_TIMEOUT_SECONDS))
                .socketTimeout(Duration.ofSeconds(LD_SOCKET_TIMEOUT_SECONDS)))
            .events(Components.sendEvents().flushInterval(Duration.ofSeconds(FLUSH_INTERVAL)))
            .build();`

`new LDClient(credentials.get(ApiConstants.LD_CLIENT_CREDS_KEY), ldConfig);`

After a while of running, started getting - [Multiple Times]

`com.launchdarkly.shaded.com.launchdarkly.eventsource.StreamClosedByServerException: Stream closed by server
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventParser.getNextChunk(EventParser.java:272)
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventParser.tryNextEvent(EventParser.java:130)
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventParser.nextEvent(EventParser.java:109)
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventSource.requireEvent(EventSource.java:598)
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventSource.access$1200(EventSource.java:58)
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventSource$IteratorImpl.hasNext(EventSource.java:571)
	at com.launchdarkly.sdk.server.StreamProcessor.lambda$start$1(StreamProcessor.java:188)`

 

`Error in stream connection (will retry): com.launchdarkly.shaded.com.launchdarkly.eventsource.StreamClosedByServerException: Stream closed by server`
  |  

<br class="Apple-interchange-newline">

**Comment by vojkozel96** [comment]
Hi, we use the SDK version `7.6.0` and can see those issues happening regularly daily. It's annoying cuz it triggers our alerts several times per day. Could you somehow look at it and handle it properly (understand not log as an error). Thank you so much!

`{"ts":"2025-01-22T13:53:59.753Z","logLevel":"WARN","thread":"LaunchDarkly-streaming","logger":"com.launchdarkly.sdk.server.LDClient.DataSource","message":"Encountered EventSource error: {}","stacktrace":"c.l.s.c.l.e.StreamClosedByServerException: Stream closed by server\n\tat c.l.s.c.l.e.EventParser.getNextChunk(EventParser.java:272)\n\tat c.l.s.c.l.e.EventParser.tryNextEvent(EventParser.java:130)\n\tat c.l.s.c.l.e.EventParser.nextEvent(EventParser.java:109)\n\tat c.l.s.c.l.e.EventSource.requireEvent(EventSource.java:598)\n\tat c.l.s.c.l.e.EventSource.access$1200(EventSource.java:58)\n\tat c.l.s.c.l.e.EventSource$IteratorImpl.hasNext(EventSource.java:571)\n\tat c.l.s.s.StreamProcessor.lambda$start$1(StreamProcessor.java:199)\n\tat java.lang.Thread.run(Thread.java:1583)\n"}`

**Comment by tomasporemba** [comment]
Hi there, @louis-launchdarkly was there any progress? Or did the team abandon/not prioritized this?

**Comment by hemanthgk10** [comment]
Hi there, I am using the SDK version 7.7.0 but still seeing the same error.

```
2025-04-29T22:23:31.274Z  WARN 1 --- [arkly-streaming] c.l.sdk.server.LDClient.DataSource       : Encountered EventSource error: {}

com.launchdarkly.shaded.com.launchdarkly.eventsource.StreamClosedByServerException: Stream closed by server
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventParser.getNextChunk(EventParser.java:272) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventParser.tryNextEvent(EventParser.java:130) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventParser.nextEvent(EventParser.java:109) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventSource.requireEvent(EventSource.java:598) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventSource.access$1200(EventSource.java:58) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at com.launchdarkly.shaded.com.launchdarkly.eventsource.EventSource$IteratorImpl.hasNext(EventSource.java:571) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at com.launchdarkly.sdk.server.StreamProcessor.lambda$start$1(StreamProcessor.java:199) ~[launchdarkly-java-server-sdk-7.7.0.jar:7.7.0]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2025-04-29T22:23:31.277Z  WARN 1 --- [arkly-streaming] c.l.sdk.server.LDClient.DataSource       : Error in stream connection (will retry): com.launchdarkly.shaded.com.launchdarkly.eventsource.StreamClosedByServerException: Stream closed by server
```
